platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: 1.1028.0

inputs:
- name: concourse-gcp-tf-bootstrap
- name: tfstate

run:
  path: concourse-gcp-tf-bootstrap/tasks/teardown.sh

params:
  BILLING_ACCOUNT_ID:
  BUCKET_LOCATION:
  FOLDER_NAME:
  GCP_CREDENTIALS_JSON:
  ORGANIZATION_ID:
  PROJECT_ID:
  PROJECT_NAME:
